### ISSUE TITLE
Most recent update prevents addUsers from creating "root" users on VMs

### ISSUE THREAD

**Issue by Grandomthoughts** [unix-ninja/hackersandbox#3]
Thanks for the update to fix the alloc error.  This (or maybe the engine change) seems to introduce a bug where only the first VM created can add a root user.  Can be seen in the destiny.mis pack.  The only root user added is the one on the area6 VM.

**Comment by unix-ninja** [comment]
Sorry about that! I thought I would change the behaviour of `addUser` slightly, but forgot why I had it that way originally. :)
Hopefully this is fixed now. Please download the new source and confirm, and I will close this out.

**Comment by Grandomthoughts** [comment]
Yep, that fixed the root creation issue.  Thanks!
